### ISSUE TITLE
while  starting the dev env i am getting this issue follows bellow

### ISSUE THREAD

**Issue by santhoshsvkmm** [AMoreaux/hapi-cli#6]
yarn run v1.9.4
$ node app.js
Connection DB ok mongodb://localhost/wallet
{ Error: getaddrinfo ENOTFOUND 3000
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '3000' }
 I think this because of url address but i don't know to solve it

**Comment by AMoreaux** [comment]
In `config/default.json` what are the value for host and port?

**Comment by santhoshsvkmm** [comment]
> In `config/default.json` what are the value for host and port?

hi,
   Port is 3001 and  host is 3000

**Comment by AMoreaux** [comment]
Host is a string like `localhost` or`example.com`. In your case replace 3000 by `localhost`
